[project]
name = "appliances-energy-prediction"
version = "0.1.0"
description = "MLOps project for predicting appliance energy use."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dvc[s3]>=3.67.1",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "dvc>=3.67.1",
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["."]
addopts = "-ra"
